# Generated by Django 4.1.4 on 2023-01-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
